# Files Service configuration.
# This service is responsible to manage the files uploaded by users (like images for products, etc...)
# This module is part of the community edition.

# Max image resolution in pixels, larger images are resized.
files.image.max.pixels=${FILES_IMAGE_MAX_PIXELS:1280}
# Thumbnail image resolution in pixels, larger images are resized, this is used for the thumbnail generation.
files.image.thumbnail.pixels=${FILES_IMAGE_THUMBNAIL_PIXELS:256}

# Signature secret for document signing, use a random hex string, this is used to sign the files and avoid file system
# modifications
files.signature.secret=${FILES_SIGNATURE_SECRET:4b43f30f6a457e7a1db638d02a69a4c49360b81022dac51843fef9b8f4273379}

# Quota Management
# Max files per user (0 no limit) - 1000 files
files.quota.max.files.per.user=${FILES_QUOTA_MAX_FILES_PER_USER:1000}
# Max total size of files per user in bytes (0 no limit) - 200MB
files.quota.max.total.bytes.per.user=${FILES_QUOTA_MAX_TOTAL_BYTES_PER_USER:209715200}
# Max file size in bytes (0 no limit) - 6MB
files.quota.max.file.bytes=${FILES_QUOTA_MAX_FILE_BYTES:6291456}

# Intracom Service configuration.
# Defines how the service will broadcast messages to all the distributed instances of itself
# Medium can be memory, db or mqtt, currently only memory is implemented
files.integration.medium=${FILES_INTEGRATION_MEDIUM:memory}
files.integration.timeout.ms=${FILES_INTEGRATION_TMOUT:10000}
