### ###########################################################
### USER MANAGEMENT API USAGE EXEMPLE

### ------------------------------------
### Step 0 : Environment Variables to setup

@apiserver=http://localhost:8091
@userEmail=john.doe@foo.bar

### ------------------------------------
### Step 1: User Registration request 
### Register a user
POST {{apiserver}}/users/1.0/registration/register
Content-Type: application/json

{
  "email" : "{{userEmail}}",
  "registrationCode" : ""
}

### ------------------------------------
### Step 2: get the validationID from the email or the database

@validationID=982B80AB8EBB12C779D698EB389E9AE0FAEA02CD983E2BDB3A40A86C570C090D48253DBE86E5D3EF254FC371D3C1834B62980C821ABF21B27CB1832D3E8DB6AD



### Create the user
POST {{apiserver}}/users/1.0/creation/create
Content-Type: application/json

{
  "email" : "{{userEmail}}",
  "password" : "changeme",
  "conditionValidation" : true,
  "validationID" : "{{validationID}}"
}

### ------------------------------------
### Step 3: Sign in

POST {{apiserver}}/users/1.0/session/signin
Content-Type: application/json

{
  "email" : "{{userEmail}}",
  "password" : "changeme"
}

### Get token and login from the reponse
@jwtToken=eyJ0eXAiOiJKV1QiLCJzdWIiOiI5NjhBMDQ5NDgwMDU3RTRFREU2NjdERkZERTBERTUzRENBRDUyMjlGNEZFQTI5QkUzMjRGQjIyOThDNTNCMEIxIiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiI5NjhBMDQ5NDgwMDU3RTRFREU2NjdERkZERTBERTUzRENBRDUyMjlGNEZFQTI5QkUzMjRGQjIyOThDNTNCMEIxIiwiZXhwIjoxNzQ1Nzg1MTc0LCJyb2xlcyI6WyJST0xFX0xPR0lOXzFGQSIsIlJPTEVfUEVORElOR19VU0VSIiwiUk9MRV9SRUdJU1RFUkVEX1VTRVIiLCJST0xFX0xPR0lOX0NPTVBMRVRFIl19.CSr-uMXkpUEfNBzaWZeOVWezYJtGuHEigeoRS7q3GUMJQySQd5zWLllA4urv2Fu-TO1U4xkCztkQFXmcSxu93Q
@login=968A049480057E4EDE667DFFDE0DE53DCAD5229F4FEA29BE324FB2298C53B0B1


### ------------------------------------
### Step 4 : Get user basic informations
GET {{apiserver}}/users/1.0/profile/basic
Authorization: Bearer {{jwtToken}}

### -------------------------------------
### Step 5 : Password change
PUT {{apiserver}}/users/1.0/profile/password/change
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "password" : "changeme2",
  "changeKey" : ""
}

### -------------------------------------
### Step 6 : Login new password
POST {{apiserver}}/users/1.0/session/signin
Content-Type: application/json

{
  "email" : "{{userEmail}}",
  "password" : "changeme2"
}

### -------------------------------------
### Step 7 : Password Lost Reset

POST {{apiserver}}/users/1.0/profile/password/request
Content-Type: application/json

{
  "email" : "{{userEmail}}"
}

### Get the lost password ID from the email or the database
@lostPasswordID=782E2E1DFCE6D06C66BEDBB70B0112400324AEC014356889C67A7426A3093FF57B30028E5DBF9EBA3F49953092140D90439BA3703467358278DA24891D0D5B3C

### -------------------------------------
### Step 8 : Lost password reset
PUT {{apiserver}}/users/1.0/profile/password/reset
Content-Type: application/json

{
  "password" : "changeme",
  "changeKey" : "{{lostPasswordID}}"
}

### -------------------------------------
### Step 9 : Logout the user
GET {{apiserver}}/users/1.0/session/signout
Authorization: Bearer {{jwtToken}}

### -------------------------------------
### Step 9bis : Verify the user can't access the API anymore
GET {{apiserver}}/users/1.0/profile/basic
Authorization: Bearer {{jwtToken}}

### -------------------------------------
### Step 10 : Upgarde a session to get a new JWT token
GET {{apiserver}}/users/1.0/session/upgrade
Authorization: Bearer {{jwtToken}}